//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.IO;
using System.IO.Compression;

namespace NSZip {

    public class zipDriver {
        [STAThread()]
        public static void Main(string[] args) {
            ZipArchive za;
            const string ZIP_NAME = "test.zip";
            ZipArchiveMode mode;
            int nargs, len;
            string anArg, zipName;
            bool showHelp;

            if ((nargs=args.Length)>0) {
                for (int i = 0 ; i<nargs ; i++) {
                    anArg=args[i];
                    if ((len=anArg.Length)>=2) {
                        if (anArg[0]=='-'||anArg[0]=='/') {
                            switch (anArg[1]) {
                                case 'o':
                                if (len>2)
                                    zipName=anArg.Substring(2).Trim();
                                else { zipName=args[i+1]; i++; }
                                break;
                                case 'h': showHelp=true; break;
                                case '?': showHelp=true; break;
                            }
                        }
                    }
                }
            }

            if (!File.Exists(ZIP_NAME))
                mode=ZipArchiveMode.Create;
            else
                mode=ZipArchiveMode.Update; ;
            using (FileStream fs = new FileStream(ZIP_NAME, FileMode.OpenOrCreate)) {
                za=new ZipArchive(fs, mode, true);
            }
        }
    }
}